version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  web:
    build: .
    tty: true
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db

#  nginx:
#    image: nginx:latest
#    restart: always
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    env_file:
#      - ./.env
#    depends_on:
#      - db
#      - web
#    ports:
#      - "82:82"
#      - "442:442"

volumes:
  postgres_data: