# Generated by Django 4.1.7 on 2023-03-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangocard',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
