# Generated by Django 4.1.7 on 2023-03-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0003_alter_mangocard_genre_alter_mangocard_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangocard',
            name='genre',
            field=models.ManyToManyField(related_name='card', to='mango.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='mangocard',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='mango.type', verbose_name='Тип'),
        ),
    ]
