# Generated by Django 4.1.7 on 2023-03-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0004_alter_mangocard_genre_alter_mangocard_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_title',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type_title',
            new_name='type',
        ),
    ]
