# Generated by Django 4.1.7 on 2023-03-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0005_rename_genre_title_genre_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='genre_title',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='type_title',
        ),
    ]
