from .base import *

AUTH_PASSWORD_VALIDATORS = AUTH_PASSWORD_VALIDATORS

ROOT_URLCONF = 'main.urls'

INSTALLED_APPS = INSTALLED_APPS

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = [STATIC_DIR]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')